akka.http.cors {
  allowed-origins = ["*"]
  allowed-headers = ["Content-Type", "Authorization"]
}

akka.javasdk.agent {
  model-provider = googleai-gemini
  googleai-gemini {
    model-name = "gemini-2.0-flash"
    api-key = ${?GOOGLE_AI_GEMINI_API_KEY}
  }
}
